# Generated by Django 2.2 on 2019-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.TextField(blank=True),
        ),
    ]
